openapi: "3.0.1"
info:
  title: "ConnectedCar_Admin_API"
  version: "1.0"
x-amazon-apigateway-request-validators:
  all:
    validateRequestBody: true
    validateRequestParameters: true 
x-amazon-apigateway-request-validator: all
paths:
  /admin/dealers:
    post: # create dealer
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Dealer' 
      security:
      - api_key: []
      x-amazon-apigateway-integration:
        type: "http_proxy"
        connectionType: "VPC_LINK"
        connectionId: 
          Fn::Sub: ${VPCLink}
        httpMethod: "POST"
        uri: 
          Fn::Sub: http://${NetworkLoadBalancerDns}/admin/dealers
    get: # get dealers
      parameters:
      - name: "stateCode"
        in: "query"
        required: true
        schema:
          $ref: '#/components/schemas/StateCode' 
      responses:
        '200':
          description: A list of dealers by stateCode
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Dealers'
      security:
      - api_key: []
      x-amazon-apigateway-integration:
        type: "http_proxy"
        connectionType: "VPC_LINK"
        connectionId: 
          Fn::Sub: ${VPCLink}
        httpMethod: "GET"
        uri: 
          Fn::Sub: http://${NetworkLoadBalancerDns}/admin/dealers
  /admin/dealers/{dealerId}:
    get: # get dealer
      parameters:
      - name: "dealerId"
        in: "path"
        required: true
        schema:
          $ref: '#/components/schemas/Guid' 
      responses:
        '200':
          description: An individual dealer by dealerId
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Dealer'
      security:
      - api_key: []
      x-amazon-apigateway-integration:
        type: "http_proxy"
        connectionType: "VPC_LINK"
        connectionId: 
          Fn::Sub: ${VPCLink}
        httpMethod: "GET"
        requestParameters:
          integration.request.path.dealerId: "method.request.path.dealerId"
        uri: 
          Fn::Sub: http://${NetworkLoadBalancerDns}/admin/dealers/{dealerId}
  /admin/dealers/{dealerId}/timeslots:
    post: # create timeslot
      parameters:
      - name: "dealerId"
        in: "path"
        required: true
        schema:
          $ref: '#/components/schemas/Guid' 
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Timeslot' 
      security:
      - api_key: []
      x-amazon-apigateway-integration:
        type: "http_proxy"
        connectionType: "VPC_LINK"
        connectionId: 
          Fn::Sub: ${VPCLink}
        httpMethod: "POST"
        requestParameters:
          integration.request.path.dealerId: "method.request.path.dealerId"
        uri: 
          Fn::Sub: http://${NetworkLoadBalancerDns}/admin/dealers/{dealerId}/timeslots
    get: # get timeslots
      parameters:
      - name: "startDate"
        in: "query"
        required: true
        schema:
          $ref: '#/components/schemas/Date' 
      - name: "endDate"
        in: "query"
        required: true
        schema:
          $ref: '#/components/schemas/Date' 
      - name: "dealerId"
        in: "path"
        required: true
        schema:
          $ref: '#/components/schemas/Guid' 
      responses:
        '200':
          description: A list of timeslots for a dealer
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Timeslots'
      security:
      - api_key: []
      x-amazon-apigateway-integration:
        type: "http_proxy"
        connectionType: "VPC_LINK"
        connectionId: 
          Fn::Sub: ${VPCLink}
        httpMethod: "GET"
        requestParameters:
          integration.request.path.dealerId: "method.request.path.dealerId"
        uri: 
          Fn::Sub: http://${NetworkLoadBalancerDns}/admin/dealers/{dealerId}/timeslots
  /admin/dealers/{dealerId}/timeslots/{serviceDateHour}:
    get: # get timeslot
      parameters:
      - name: "dealerId"
        in: "path"
        required: true
        schema:
          $ref: '#/components/schemas/Guid' 
      - name: "serviceDateHour"
        in: "path"
        required: true
        schema:
          $ref: '#/components/schemas/ServiceDateHour' 
      responses:
        '200':
          description: An individual timeslot
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Timeslot'
      security:
      - api_key: []
      x-amazon-apigateway-integration:
        type: "http_proxy"
        connectionType: "VPC_LINK"
        connectionId: 
          Fn::Sub: ${VPCLink}
        httpMethod: "GET"
        requestParameters:
          integration.request.path.dealerId: "method.request.path.dealerId"
          integration.request.path.serviceDateHour: "method.request.path.serviceDateHour"
        uri: 
          Fn::Sub: http://${NetworkLoadBalancerDns}/admin/dealers/{dealerId}/timeslots/{serviceDateHour}
  /admin/customers:
    post: # create customer
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CustomerProvision' 
      security:
      - api_key: []
      x-amazon-apigateway-integration:
        type: "http_proxy"
        connectionType: "VPC_LINK"
        connectionId: 
          Fn::Sub: ${VPCLink}
        httpMethod: "POST"
        uri: 
          Fn::Sub: http://${NetworkLoadBalancerDns}/admin/customers
    get: # get customers
      parameters:
      - name: "lastname"
        in: "query"
        schema:
          $ref: '#/components/schemas/Text' 
      responses:
        '200':
          description: A list of customers by lastname
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Customers'
      security:
      - api_key: []
      x-amazon-apigateway-integration:
        type: "http_proxy"
        connectionType: "VPC_LINK"
        connectionId: 
          Fn::Sub: ${VPCLink}
        httpMethod: "GET"
        uri: 
          Fn::Sub: http://${NetworkLoadBalancerDns}/admin/customers
  /admin/customers/{username}:
    get: # get customer
      parameters:
      - name: "username"
        in: "path"
        required: true
        schema:
          $ref: '#/components/schemas/AlphaNumeric' 
      responses:
        '200':
          description: An individual customer by username
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Customer'
      security:
      - api_key: []
      x-amazon-apigateway-integration:
        type: "http_proxy"
        connectionType: "VPC_LINK"
        connectionId: 
          Fn::Sub: ${VPCLink}
        httpMethod: "GET"
        requestParameters:
          integration.request.path.username: "method.request.path.username"
        uri: 
          Fn::Sub: http://${NetworkLoadBalancerDns}/admin/customers/{username}
  /admin/customers/{username}/registrations:
    post: # create registration
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Registration' 
      parameters:
      - name: "username"
        in: "path"
        required: true
        schema:
          $ref: '#/components/schemas/AlphaNumeric' 
      security:
      - api_key: []
      x-amazon-apigateway-integration:
        type: "http_proxy"
        connectionType: "VPC_LINK"
        connectionId: 
          Fn::Sub: ${VPCLink}
        httpMethod: "POST"
        requestParameters:
          integration.request.path.username: "method.request.path.username"
        uri: 
          Fn::Sub: http://${NetworkLoadBalancerDns}/admin/customers/{username}/registrations
    patch: # update registration
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/RegistrationPatch' 
      parameters:
      - name: "username"
        in: "path"
        required: true
        schema:
          $ref: '#/components/schemas/AlphaNumeric' 
      security:
      - api_key: []
      x-amazon-apigateway-integration:
        type: "http_proxy"
        connectionType: "VPC_LINK"
        connectionId: 
          Fn::Sub: ${VPCLink}
        httpMethod: "PATCH"
        requestParameters:
          integration.request.path.username: "method.request.path.username"
        uri: 
          Fn::Sub: http://${NetworkLoadBalancerDns}/admin/customers/{username}/registrations
    get: # get registrations
      parameters:
      - name: "username"
        in: "path"
        required: true
        schema:
          $ref: '#/components/schemas/AlphaNumeric' 
      responses:
        '200':
          description: A list of vehicle registrations for a customer
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Registrations'
      security:
      - api_key: []
      x-amazon-apigateway-integration:
        type: "http_proxy"
        connectionType: "VPC_LINK"
        connectionId: 
          Fn::Sub: ${VPCLink}
        httpMethod: "GET"
        requestParameters:
          integration.request.path.username: "method.request.path.username"
        uri: 
          Fn::Sub: http://${NetworkLoadBalancerDns}/admin/customers/{username}/registrations
  /admin/customers/{username}/registrations/{vin}:
    get: # get registration
      parameters:
      - name: "username"
        in: "path"
        required: true
        schema:
          $ref: '#/components/schemas/AlphaNumeric' 
      - name: "vin"
        in: "path"
        required: true
        schema:
          $ref: '#/components/schemas/AlphaNumeric' 
      responses:
        '200':
          description: An individual registration
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Registration'
      security:
      - api_key: []
      x-amazon-apigateway-integration:
        type: "http_proxy"
        connectionType: "VPC_LINK"
        connectionId: 
          Fn::Sub: ${VPCLink}
        httpMethod: "GET"
        requestParameters:
          integration.request.path.username: "method.request.path.username"
          integration.request.path.vin: "method.request.path.vin"
        uri: 
          Fn::Sub: http://${NetworkLoadBalancerDns}/admin/customers/{username}/registrations/{vin}
  /admin/vehicles:
    post: # create vehicle
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Vehicle' 
      security:
      - api_key: []
      x-amazon-apigateway-integration:
        type: "http_proxy"
        connectionType: "VPC_LINK"
        connectionId: 
          Fn::Sub: ${VPCLink}
        httpMethod: "POST"
        uri: 
          Fn::Sub: http://${NetworkLoadBalancerDns}/admin/vehicles
  /admin/vehicles/{vin}:
    get: # get vehicle
      parameters:
      - name: "vin"
        in: "path"
        required: true
        schema:
          $ref: '#/components/schemas/AlphaNumeric' 
      responses:
        '200':
          description: An individual vehicle by vin
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Vehicle'
      security:
      - api_key: []
      x-amazon-apigateway-integration:
        type: "http_proxy"
        connectionType: "VPC_LINK"
        connectionId: 
          Fn::Sub: ${VPCLink}
        httpMethod: "GET"
        requestParameters:
          integration.request.path.vin: "method.request.path.vin"
        uri: 
          Fn::Sub: http://${NetworkLoadBalancerDns}/admin/vehicles/{vin}
  /admin/vehicles/{vin}/registrations:
    get: # get vehicle registrations
      parameters:
      - name: "vin"
        in: "path"
        required: true
        schema:
          $ref: '#/components/schemas/AlphaNumeric' 
      responses:
        '200':
          description: A list of registrations for a vehicle
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Registrations'
      security:
      - api_key: []
      x-amazon-apigateway-integration:
        type: "http_proxy"
        connectionType: "VPC_LINK"
        connectionId: 
          Fn::Sub: ${VPCLink}
        httpMethod: "GET"
        requestParameters:
          integration.request.path.vin: "method.request.path.vin"
        uri: 
          Fn::Sub: http://${NetworkLoadBalancerDns}/admin/vehicles/{vin}/registrations
components:
  securitySchemes:
    api_key:
      type: "apiKey"
      name: "x-api-key"
      in: "header"
