version: 0.2
env:
  exported-variables:
    - VERSION_NUMBER
phases:
  install:
    runtime-versions:
      java: corretto11
  pre_build:
    commands:
      - VERSION_NUMBER=$(date +"%Y%m%d-%H%M%S")
  build:
    commands:
      - mvn install -q -f main/pom.xml
  post_build:
    commands:
      - aws s3 rm --recursive s3://${BUCKET}/${SERVICE}/${ENVIRONMENT}
      - aws s3 cp main/authorizers/target/authorizers-SNAPSHOT-AUTHORIZERS.jar s3://${BUCKET}/${SERVICE}/${ENVIRONMENT}/authorizers-${VERSION_NUMBER}.jar
      - aws s3 cp main/functions/target/functions-SNAPSHOT-FUNCTIONS.jar s3://${BUCKET}/${SERVICE}/${ENVIRONMENT}/functions-${VERSION_NUMBER}.jar
      - aws s3 cp deployment/sam/templates/admin.yaml s3://${BUCKET}/${SERVICE}/${ENVIRONMENT}/admin.yaml
      - aws s3 cp deployment/sam/templates/vehicle.yaml s3://${BUCKET}/${SERVICE}/${ENVIRONMENT}/vehicle.yaml
      - aws s3 cp deployment/sam/templates/master.yaml s3://${BUCKET}/${SERVICE}/${ENVIRONMENT}/master.yaml
      - aws s3 cp deployment/sam/templates/customer.yaml s3://${BUCKET}/${SERVICE}/${ENVIRONMENT}/customer.yaml
      - aws s3 cp deployment/sam/templates/services.yaml s3://${BUCKET}/${SERVICE}/${ENVIRONMENT}/services.yaml




